"use client";

import { useSearchParams } from "next/navigation";
import { Suspense, useEffect, useState } from "react";
import Link from "next/link";
import { PermitCard } from "@/components/permit-card";
import { UrgencyBadge } from "@/components/urgency-badge";
import { runPermitLookup } from "@/lib/permit-lookup";
import { type Trade, type JobType } from "@/lib/permit-database";
import { seasonalUrgency } from "@/lib/timeline-estimator";
import { jsPDF } from "jspdf";
import { Download, ArrowLeft, Clock, AlertTriangle } from "lucide-react";

const TRADE_LABELS: Record<Trade, string> = {
  hvac: "HVAC",
  plumbing: "Plumbing",
  electrical: "Electrical",
  general: "General Contracting",
};

const JOB_TYPE_LABELS: Record<JobType, string> = {
  new_install: "New Installation",
  replacement: "Replacement",
  repair: "Repair",
  addition: "Addition",
  maintenance: "Maintenance",
};

function PermitsContent() {
  const searchParams = useSearchParams();
  const trade = searchParams.get("trade") as Trade;
  const jobType = searchParams.get("jobType") as JobType;
  const zip = searchParams.get("zip") || "";

  const [result, setResult] = useState<ReturnType<typeof runPermitLookup> | null>(null);
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    if (!trade || !jobType) return;
    const lookupResult = runPermitLookup({ trade, jobType, zip });
    setResult(lookupResult);

    // Save to localStorage history
    const history = JSON.parse(localStorage.getItem("permit_history") || "[]");
    const entry = {
      id: Date.now().toString(),
      trade,
      jobType,
      zip,
      date: new Date().toISOString(),
      permitCount: lookupResult.totalPermits,
    };
    history.unshift(entry);
    localStorage.setItem("permit_history", JSON.stringify(history.slice(0, 20)));
    setSaved(true);
  }, [trade, jobType, zip]);

  if (!trade || !jobType) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <div className="text-center">
          <p className="text-slate-600 mb-4">No lookup parameters provided.</p>
          <Link href="/lookup/" className="text-blue-600 hover:underline">← Back to Lookup</Link>
        </div>
      </div>
    );
  }

  if (!result) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <p className="text-slate-600">Loading permits...</p>
      </div>
    );
  }

  const seasonNote = seasonalUrgency(trade, jobType);

  const exportPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(16);
    doc.text("PermitPilot AI — Permit Checklist", 20, 20);
    doc.setFontSize(11);
    doc.text(`${TRADE_LABELS[trade]} — ${JOB_TYPE_LABELS[jobType]}${zip ? ` — ZIP: ${zip}` : ""}`, 20, 30);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 38);
    doc.line(20, 42, 190, 42);

    let y = 50;
    result.permits.forEach((p, i) => {
      doc.setFontSize(12);
      doc.text(`${i + 1}. ${p.name}`, 20, y);
      y += 7;
      doc.setFontSize(9);
      doc.text(`   Authority: ${p.authority}`, 20, y);
      y += 5;
      doc.text(`   Fee: ${p.feeRange}  |  Processing: ${p.processingDays}  |  Urgency: ${p.urgency}`, 20, y);
      if (p.urgencyNote) {
        y += 5;
        doc.text(`   Note: ${p.urgencyNote}`, 20, y);
      }
      y += 10;
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
    });

    doc.setFontSize(9);
    doc.text("Generated by PermitPilot AI — permitpilot.ai", 20, 285);
    doc.save(`permit-checklist-${trade}-${jobType}.pdf`);
  };

  const highUrgencyPermits = result.permits.filter(p => p.urgency === "high");

  return (
    <div className="min-h-screen bg-slate-50 py-12 px-6">
      <div className="max-w-3xl mx-auto">
        {/* Header */}
        <div className="flex items-center gap-4 mb-8">
          <Link href="/lookup/" className="flex items-center gap-1 text-slate-600 hover:text-slate-900 text-sm">
            <ArrowLeft className="h-4 w-4" />
            New Lookup
          </Link>
          <span className="text-slate-300">|</span>
          <span className="text-sm text-slate-500">{saved ? "✓ Saved to history" : "Saving..."}</span>
        </div>

        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-6 mb-6">
          <h1 className="text-2xl font-bold text-slate-900 mb-1">
            {TRADE_LABELS[trade]} — {JOB_TYPE_LABELS[jobType]}
          </h1>
          {zip && <p className="text-slate-500 text-sm mb-4">ZIP: {zip}</p>}

          {/* Summary stats */}
          <div className="grid grid-cols-3 gap-4 mb-4">
            <div className="bg-blue-50 rounded-xl p-4 text-center">
              <div className="text-2xl font-bold text-blue-700">{result.totalPermits}</div>
              <div className="text-xs text-blue-600">Total Permits</div>
            </div>
            <div className="bg-red-50 rounded-xl p-4 text-center">
              <div className="text-2xl font-bold text-red-700">{highUrgencyPermits.length}</div>
              <div className="text-xs text-red-600">High Urgency</div>
            </div>
            <div className="bg-slate-50 rounded-xl p-4 text-center">
              <div className="text-lg font-bold text-slate-700">${result.estimatedTotalFees}</div>
              <div className="text-xs text-slate-500">Fee Range</div>
            </div>
          </div>

          {/* Seasonal urgency banner */}
          {seasonNote && (
            <div className="flex items-start gap-3 p-4 bg-amber-50 border border-amber-200 rounded-xl mb-4">
              <AlertTriangle className="h-5 w-5 text-amber-600 mt-0.5 shrink-0" />
              <p className="text-sm text-amber-800">{seasonNote}</p>
            </div>
          )}
        </div>

        {/* Permit Cards */}
        <div className="space-y-4 mb-8">
          {result.permits.map((permit, i) => (
            <PermitCard key={i} permit={permit} />
          ))}
        </div>

        {/* Actions */}
        <div className="flex flex-col sm:flex-row gap-4">
          <button
            onClick={exportPDF}
            className="flex items-center justify-center gap-2 bg-blue-600 hover:bg-blue-500 text-white px-6 py-3 rounded-xl font-semibold transition"
          >
            <Download className="h-4 w-4" />
            Download Permit Checklist (PDF)
          </button>
          <Link href="/history/" className="flex items-center justify-center gap-2 border border-slate-300 hover:border-slate-400 text-slate-700 px-6 py-3 rounded-xl font-medium transition">
            <Clock className="h-4 w-4" />
            View History
          </Link>
          <Link href="/checkout/" className="flex items-center justify-center gap-2 bg-green-600 hover:bg-green-500 text-white px-6 py-3 rounded-xl font-semibold transition">
            Get Pro — $19/mo
          </Link>
        </div>
      </div>
    </div>
  );
}

export default function PermitsPage() {
  return (
    <Suspense fallback={<div className="min-h-screen bg-slate-50 flex items-center justify-center"><p className="text-slate-600">Loading...</p></div>}>
      <PermitsContent />
    </Suspense>
  );
}
