"use client";

import { jsPDF } from "jspdf";
import { TipCalculationResult, formatCurrency } from "@/lib/tip-calculator";
import { ComplianceResult } from "@/lib/compliance-checker";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";

interface ExportPDFProps {
  calculation: TipCalculationResult;
  compliance: ComplianceResult;
}

export function ExportPDF({ calculation, compliance }: ExportPDFProps) {
  const generatePDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text("TipTrail AI — Weekly Tip Report", pageWidth / 2, 20, { align: "center" });

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Generated: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, pageWidth / 2, 28, { align: "center" });

    if (calculation.dateRange.start) {
      doc.text(`Period: ${calculation.dateRange.start} to ${calculation.dateRange.end}`, pageWidth / 2, 34, { align: "center" });
    }

    // Divider
    doc.setLineWidth(0.5);
    doc.line(20, 40, pageWidth - 20, 40);

    // Summary
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Summary", 20, 52);

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text(`Total Tips Collected: ${formatCurrency(calculation.totalTips)}`, 20, 62);
    doc.text(`Total Hours Worked: ${calculation.totalHours.toFixed(1)} hrs`, 20, 70);
    doc.text(`Total Tip-Out: ${formatCurrency(calculation.tipOutTotal)}`, 20, 78);
    doc.text(`California Mode: ${calculation.isCalifornia ? "Yes" : "No"}`, 20, 86);

    // Allocations
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Employee Allocations", 20, 100);

    let yPos = 110;
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Employee", 20, yPos);
    doc.text("Role", 80, yPos);
    doc.text("Hours", 120, yPos);
    doc.text("$/Hr", 140, yPos);
    doc.text("Tip Amount", 165, yPos);
    yPos += 6;
    doc.line(20, yPos, pageWidth - 20, yPos);
    yPos += 6;

    doc.setFont("helvetica", "normal");
    calculation.allocations.forEach((alloc) => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
      doc.text(alloc.employee.name.substring(0, 25), 20, yPos);
      doc.text(alloc.employee.role.replace("-", " "), 80, yPos);
      doc.text(alloc.employee.hoursWorked.toFixed(1), 120, yPos);
      doc.text(formatCurrency(alloc.hourlyRate), 140, yPos);
      doc.text(formatCurrency(alloc.totalTip), 165, yPos);
      yPos += 8;
    });

    // Compliance
    yPos += 10;
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Compliance Status", 20, yPos);
    yPos += 10;

    doc.setFontSize(10);
    const complianceColor = compliance.passed ? [0, 128, 0] : [220, 53, 69];
    doc.setTextColor(complianceColor[0], complianceColor[1], complianceColor[2]);
    doc.text(`Status: ${compliance.passed ? "PASSED" : "FAILED"}`, 20, yPos);
    yPos += 8;
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "normal");

    compliance.issues.forEach((issue) => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
      const prefix = issue.severity === "error" ? "❌" : issue.severity === "warning" ? "⚠️" : "ℹ️";
      const lines = doc.splitTextToSize(`${prefix} [${issue.code}] ${issue.message} (${issue.reference})`, pageWidth - 50);
      doc.text(lines, 20, yPos);
      yPos += lines.length * 5 + 4;
    });

    // Footer
    const footerY = doc.internal.pageSize.getHeight() - 15;
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text("Generated by TipTrail AI — tip.tiptrail.ai — For DLSE compliance retention: keep this record for 3 years.", pageWidth / 2, footerY, { align: "center" });

    doc.save(`tiptrail-report-${new Date().toISOString().split("T")[0]}.pdf`);
  };

  return (
    <Button onClick={generatePDF} variant="outline" size="sm" className="gap-2">
      <Download className="h-4 w-4" />
      Download PDF Report
    </Button>
  );
}
